### ISSUE TITLE
I would like to get real-time open prices

### ISSUE THREAD

**Issue by jiany30** [sandrinr/tdapiclient-python#1]
I would like to get real-time open prices
So I am going to draw this plot
![Screenshot_1](https://user-images.githubusercontent.com/62179052/78970790-b8636f80-7b3c-11ea-848d-e9b7d835f68a.png)
But I can't get the prices now.
Can you help me?
Best regards!

**Comment by sandrinr** [comment]
Hi @jiany30 

This API binding is in its early stages and only supports what I currently need. You are welcome to open a pull request for functionality you might need.

You can get current quotes already with the `TDMarketdata` object. However, historical data, which you need to plot the graph you show, is not (yet) implemented.

I am going to close this issue, as it does not describe a bug of an existing feature.
